version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
#    image: mcp-server-starter:latest
    container_name: mcp-server-starter
    ports:
      - "3000:3000"
    environment:
      # MCP Server Configuration
      MCP_SERVER_NAME: mcp-server-starter
      MCP_SERVER_VERSION: "1.0.0"
      
      # Transport Configuration
      TRANSPORT_TYPE: http
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: "3000"
      
      # OAuth Configuration
      AUTH_ENABLED: "true"
      OAUTH_PROXY_ENABLED: "true"
      OAUTH_PROVIDER: google
      
      # Public URL (update this for your deployment)
      PUBLIC_URL: https://dev.anatoly.dev
      
      # Security - IP Filtering (uncomment to enable)
      # FILTER_BY_IP: "127.0.0.1,192.168.1.0/24"
      
      # Security - Email Filtering (uncomment to enable)
      # ALLOWED_EMAILS: "test@example.com,admin@company.org"
      
      # Logging
      LOG_LEVEL: info
      REQUEST_LOGGING: "true"
      
    restart: unless-stopped